//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateXML
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ORDER_HEADER
    {
        public string RARefNum { get; set; }
        public string WMSRefNum { get; set; }
        public string Customer { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> ExpShippedDate { get; set; }
        public Nullable<System.DateTime> LastShippedDate { get; set; }
        public string CustomerOrderReference { get; set; }
        public string CustomerShipmentNo { get; set; }
        public string CustomerSONo { get; set; }
        public string CustomerInvoiceNo { get; set; }
        public string SupplierId { get; set; }
        public string SupplierName { get; set; }
        public string TransportMode { get; set; }
        public string ShipmentNo { get; set; }
        public string DocumentNo { get; set; }
        public string CustomerReference1 { get; set; }
        public string CustomerReference2 { get; set; }
        public string ReferenceInfo1 { get; set; }
        public string ReferenceInfo2 { get; set; }
        public string ConsigneeId { get; set; }
        public string ConsigneeName { get; set; }
        public string ConsigneeAddress { get; set; }
        public string CarrierId { get; set; }
        public string CarrierName { get; set; }
        public string CarrierAddress { get; set; }
    }
}
