//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateXML
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ORDER_DETAIL
    {
        public string RARefNum { get; set; }
        public int RARefLine { get; set; }
        public string SKU { get; set; }
        public string SKUDescription { get; set; }
        public string Package { get; set; }
        public decimal OrderedQty { get; set; }
        public decimal PickedQty { get; set; }
        public string PickedBy { get; set; }
        public Nullable<System.DateTime> PickedDate { get; set; }
        public decimal ShippedQty { get; set; }
        public string ShippedBy { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
        public string SupplierId { get; set; }
        public string SupplierName { get; set; }
        public Nullable<System.DateTime> ManufactoryDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> FIFODate { get; set; }
        public string QACode { get; set; }
        public string ReferenceInfo1 { get; set; }
        public string ReferenceInfo2 { get; set; }
    }
}
